### ISSUE TITLE
Add support for custom domains (GitHub Enterprise, self-hosted Gitea/Forgejo)

### ISSUE THREAD

**Issue by miloth** [catppuccin/github-file-explorer-icons#41]
### What feature are you envisioning?

Allow the extension to be enabled for custom GHE domains. It could use a similar strategy to [Better Pull Resquests for GitHub](https://github.com/berzniz/github_pr_tree), implemented in [this PR](https://github.com/berzniz/github_pr_tree/pull/41).

PS: I might give it a go when I find some time.

**Comment by uncenter** [comment]
Hmm, I would love to add this but I think with MV3 it is no longer possible. I tried following https://github.com/fregante/webext-dynamic-content-scripts/blob/main/how-to-add-github-enterprise-support-to-web-extensions.md but was unable to make it work due to permissions errors, see https://groups.google.com/a/chromium.org/g/chromium-extensions/c/EnUmtHWOI9o?pli=1.

**Comment by uncenter** [comment]
Ah,. actually that thread is outdated and `optional_host_permissions` is now shipped in browsers. I'll look into why it wasn't working again.

**Comment by uncenter** [comment]
This has now been released in https://github.com/catppuccin/github-file-explorer-icons/releases/tag/v0.8.0 :)

**Comment by uncenter** [comment]
Unfortunately it may take a few days for the new version to appear on the store, as it requires additional permissions and therefore may have to go under manual human review before approval.
